#!/bin/sh
echo "Content-type: text/html"
echo ""
get_post(){
     for qr in $QUERY_STRING
     do
          if [ "${qr%%=*}" == "$1" ];then
              echo ${qr##*=}| sed 's/+/ /g'
              break
          fi
     done
}
QUERY_STRING=$(echo $QUERY_STRING | sed 's/&/ /g')
QUERY_STRING=$(echo $QUERY_STRING | sed 's/%3A/:/g')
function waitForHost
{
    if [ -n "$1" ];
    then
        waitForHost1 $1
        echo "Internet Connected"
    else
        echo -e "..."
    fi
}
config_network(){
        conf_dir="/etc/config"
        config="network"
                uci -q delete network.wlan
        uci set network.wlan=interface
        uci set network.wlan.netmask='255.255.255.0'
        uci set network.wlan.proto='dhcp'
        uci commit $config
                uci set firewall.cfg04dc81.network=lan
                uci set firewall.cfg06dc81.network='wan wan6 wlan'
                S=`uci get wireless.sta.ssid | sed "s/\'//g" | sed -E 's/( )+$//'`
                uci -q set wireless.sta.ssid="$S"
                uci commit firewall
                wifi up
        waitForHost1 8.8.8.8
                /etc/init.d/firewall restart > /dev/null 2>&1
                wifi up
}
form_wifi(){
cat <<EOF
<form method="get">
        <div class="col-xs-12">
                <div class="container">
                        <label for="usr">SSID:</label>
                        <input type="text" name="ssid" class="form-control" value="$SSID" id="usr" />
                        <label for="pwd">PASSWORD:</label>
                        <input type="password" name="key" class="form-control" value="$KEY" id="pwd" />
                        <div class="form-group">
                                <div class="input-group" style="display:block;;">
                                        <input type="submit" name="submit" value="check" class="form-control" >
                                        <input type="submit" name="scan" value="scan" class="form-control" >
                                </div>
                        </div>
                        <pre style="overflow-x:hidden" class="container text-center">
                                $(setup)
                                $(scan)
                        </pre>
                </div>
        </div>
</form>
EOF
}
device_info(){
cat <<EOF
<form method="get">
        <div class="col-xs-12">
                <div class="container">
                <pre style="overflow-x:hidden" class="container text-center">
EOF
ST=`cat /proc/cpuinfo | egrep "system|machine" | cut -d':' -f2- | sed -e '/\ / s/^\ *//' | head -1`
MC=`cat /proc/cpuinfo | egrep "system|machine" | cut -d':' -f2- | sed -e '/\ / s/^\ *//' | tail -1`
divider===============================
divider=$divider$divider

header="\n %-22s %8s %10s\n"
format=" %-22s %12s %10s\n"
width=50
printf "$header" "SYSTEM TYPE" "MACHINE"
printf "%$width.${width}s\n" "$divider"
printf "$format" "`echo $ST`" "`echo $MC`"
cat <<EOF
                </pre>
                </div>
         </div>
</form>
EOF
}
config_wireless(){
                SSID=`echo "$@"|sed 's:.*--sid ::'|cut -d'-' -f1`
                KEY=`echo "$@"|sed 's:.*--key ::'|cut -d'-' -f1`
        conf_dir="/etc/config"
        config="wireless"
                uci -q delete wireless.sta
        rm -rf $conf_dir/$config
        wifi config
        sed -i 's/default_radio0/ap/' $conf_dir/$config
        uci -q set wireless.ap.ssid='FDI-LEDE'
        uci -q set wireless.ap.encryption=psk2
        uci -q set wireless.ap.key='1234567890'
        uci commit $config
                uci -q set wireless.sta=wifi-iface
                uci -q set wireless.sta.network='wlan'
                uci -q set wireless.sta.encryption='psk2'
                uci -q set wireless.sta.device='radio0'
                uci -q set wireless.sta.mode='sta'
                uci -q set wireless.sta.key="$KEY"
                uci -q set wireless.sta.ssid="$SSID"
                uci -q set wireless.radio0.disabled='0'
                uci commit $config
                wifi up
                config_network
}
ERROR="ISI TERLEBIH DAHULU \nSSID DAN PASSWORDNYA"
scan(){
ERROR=""
if [ "$(get_post scan)" == "scan" ];then
        echo "<div class=''>"
        n=1
        echo "<h2 style='margin-top:-30px;'>wifi detected list</h2>"
        for i in $(iw wlan0 scan | grep SSID | awk -F':' '{print $2}' | sed -e 's/^\ *//');do
           printf "%s\n" "<i>$n. $i</i>"
           let n=$n+1
        done
        echo "</div>"
fi
}
function setup
{
if [ "$(get_post ssid)" != "" ] && [ "$(get_post key)" != "" ] && [ "$(get_post scan)" == "scan" ];then
if [ "$(get_post submit)" == "check" ];then
                echo "<div class='text-center'>"
                        config_wireless --sid $SSID --key $KEY
                        if [ $? == 0 ];then
                        echo SUCCESS
                        SSID="$(get_post ssid)"
                        KEY="$(get_post key)"
                        else
                        echo FILED
                        fi
                echo "</div>"
fi
else
echo "<div class='text-center'>"
        printf "$ERROR"
fi
echo "</div>"
}
function css_topnav
{
cat <<EOF
body {margin:0;}
.topnav {
  overflow: hidden;
  background-color: #333;
}
.topnav a {
  float: left;
  display: inline-block;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}
.logo {
    float: left;
    padding: 14px 16px;
    display: inline-block;
    vertical-align: top;
    width: 100px;
    height: 60px;
    margin-top: -30px;
}
#load{
position:absolute;
z-index:1;
border:3px double #999;
background:#f7f7f7;
width:300px;
height:300px;
margin-top:-150px;
margin-left:-150px;
top:50%;
left:50%;
text-align:center;
line-height:300px;
font-family:"Trebuchet MS", verdana, arial,tahoma;
font-size:18pt;
}
.topnav a:hover {
  background-color: #ddd;
  color: black;
}
.topnav .icon {
  display: none;
}
@media screen and (max-width: 600px) {
  .topnav a:not(:first-child) {display: none;}
  .topnav a.icon {
    float: right;
    display: block;
  }
}
@media screen and (max-width: 600px) {
  .topnav.responsive {position: relative;}
  .topnav.responsive .icon {
    position: absolute;
    right: 0;
    top: 0;
  }
  .topnav.responsive a {
    float: none;
    display: block;
    text-align: left;
    height: 30px;
    line-height: 1px;
  }
}
pre {
    overflow: hidden;
    overflow-y: hidden;
    font-size: 12px;
    background: #efefef;
    border: 1px solid #777;
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    box-sizing: border-box;
}
EOF
}
function js_topnav
{
cat <<EOF
function myFunction() {
    var x = document.getElementById("myTopnav");
    if (x.className === "topnav") {
        x.className += " responsive";
    } else {
        x.className = "topnav";
    }
}
EOF
}
function css_bootstrap
{
cat<<EOF
.col-xs-1, .col-xs-2, .col-xs-3, .col-xs-4, .col-xs-5, .col-xs-6,
.col-xs-7, .col-xs-8, .col-xs-9, .col-xs-10, .col-xs-11 {
    float: left;
}
.col-xs-12 { width: 100%; }
.col-xs-11 { width: 91.66666666666666%; }
.col-xs-10 { width: 83.33333333333334%; }
.col-xs-9  { width: 75%; }
.col-xs-8  { width: 66.66666666666666%; }
.col-xs-7  { width: 58.333333333333336%; }
.col-xs-6  { width: 50%; }
.col-xs-5  { width: 41.66666666666667%; }
.col-xs-4  { width: 33.33333333333333%; }
.col-xs-3  { width: 25%; }
.col-xs-2  { width: 16.666666666666664%; }
.col-xs-1  { width: 8.333333333333332%; }
// if we reach 768px, let's use -sm columns
@media (min-width: 768px) {
  .col-sm-1, .col-sm-2, .col-sm-3, .col-sm-4, .col-sm-5, .col-sm-6,
  .col-sm-7, .col-sm-8, .col-sm-9, .col-sm-10, .col-sm-11 {
      float: left;
  }
  .col-sm-12 { width: 100%; }
  .col-sm-11 { width: 91.66666666666666%; }
}
input[type=text], input[type=password] {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    box-sizing: border-box;
}
button {
    background-color: #4CAF50;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    cursor: pointer;
    width: 100%;
}
button:hover {
    opacity: 0.8;
}
.container {
    padding: 16px;
}
.text-center {
    text-align: center;
}
input[type=button], input[type=submit], input[type=reset] {
    background-color: #4CAF50;
    border: none;
    color: white;
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    text-decoration: none;
    margin: 4px 2px;
    cursor: pointer;
}
EOF
}
echo "
<html>
<head>
        <meta charset=\"utf-8\">
        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">
        <style>$(css_topnav)</style>
        <style>$(css_bootstrap)</style>
</head>
<body>
<div class=\"topnav\" id=\"myTopnav\">
        <a href=\"/cgi-bin/html\">Home</a>
        <a href=\"/cgi-bin/luci\">Luci</a>
        <a href=\"javascript:void(0);\" style=\"font-size:15px;\" class=\"icon\" onclick=\"myFunction()\">&#9776;</a>
</div>
$(device_info)
$(form_wifi)
</div>
<script type=\"text/javascript\">$(js_topnav)</script>
</body>
</html>
"
